//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LiderAppEntities : DbContext
    {
        public LiderAppEntities()
            : base("name=LiderAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<PERSONAL> PERSONAL { get; set; }
        public virtual DbSet<FORMAPAGO> FORMAPAGO { get; set; }
        public virtual DbSet<DETPEDIDO> DETPEDIDO { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<ZONA> ZONA { get; set; }
        public virtual DbSet<ZONA_PERSONAL> ZONA_PERSONAL { get; set; }
        public virtual DbSet<REPARTO> REPARTO { get; set; }
        public virtual DbSet<RUTAS> RUTAS { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
    }
}
