//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETPEDIDO
    {
        public string Pedido { get; set; }
        public string Producto { get; set; }
        public decimal PrecUnit { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Estado { get; set; }
        public string TipoPrecio { get; set; }
        public decimal TranGratuita { get; set; }
        public string lote { get; set; }
        public Nullable<System.DateTime> fvctolote { get; set; }
        public string flgSurtido { get; set; }
        public Nullable<int> IDBonificacion { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> PrecioNeto { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Recargo { get; set; }
        public Nullable<decimal> Afecto { get; set; }
        public Nullable<bool> Bonif { get; set; }
    
        public virtual PEDIDO PEDIDO1 { get; set; }
        public virtual PRODUCTO PRODUCTO1 { get; set; }
    }
}
