//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTIPO
    {
        public string DocTipo1 { get; set; }
        public string Descripcion { get; set; }
        public string Serie { get; set; }
        public Nullable<int> Numero { get; set; }
        public short Signo { get; set; }
        public string codigo { get; set; }
        public Nullable<int> PKID { get; set; }
    }
}
