//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMAPAGO
    {
        public string FormaPago1 { get; set; }
        public string Descripcion { get; set; }
        public byte PlazoMax { get; set; }
        public byte Nrodia { get; set; }
        public bool contado { get; set; }
        public byte DiasFinta { get; set; }
    }
}
