//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo
    {
        public string grupo1 { get; set; }
        public string descrip { get; set; }
        public string descorta { get; set; }
        public string orden { get; set; }
        public bool activo { get; set; }
    }
}
