//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class infrepartocab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public infrepartocab()
        {
            this.INFREPARTOes = new HashSet<INFREPARTO>();
        }
    
        public string infreparto { get; set; }
        public System.DateTime fecha { get; set; }
        public string ruta { get; set; }
        public string estado { get; set; }
        public string observa { get; set; }
        public string repartidor { get; set; }
        public decimal importe { get; set; }
        public string numerodevale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFREPARTO> INFREPARTOes { get; set; }
    }
}
