//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFREPARTO
    {
        public string InfReparto1 { get; set; }
        public string Documento { get; set; }
        public string TipoDoc { get; set; }
        public string TipoIng { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public decimal Valor { get; set; }
        public string Estado { get; set; }
        public decimal importe { get; set; }
        public decimal aliquidar { get; set; }
    
        public virtual infrepartocab infrepartocab { get; set; }
    }
}
