//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINEA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LINEA()
        {
            this.MARCAs = new HashSet<MARCA>();
        }
    
        public string Linea1 { get; set; }
        public int CanMenor { get; set; }
        public int CanMayor { get; set; }
        public string Descripcion { get; set; }
        public decimal ComiMayor { get; set; }
        public decimal ComiMenor { get; set; }
        public decimal CredMayor { get; set; }
        public decimal CredMenor { get; set; }
        public decimal ComiEspecial { get; set; }
        public decimal ComiSEspecial { get; set; }
        public string orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARCA> MARCAs { get; set; }
    }
}
