//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.DETPEDIDO = new HashSet<DETPEDIDO>();
        }
    
        public string Pedido1 { get; set; }
        public string Personal { get; set; }
        public string Cliente { get; set; }
        public string FormaPago { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public bool Reparto { get; set; }
        public string TipoPersona { get; set; }
        public bool Procesado { get; set; }
        public string rsocial { get; set; }
        public string ruc { get; set; }
        public string direccion { get; set; }
        public string dni { get; set; }
        public string encargado { get; set; }
        public string npersonal { get; set; }
        public string nencargado { get; set; }
        public string gestion { get; set; }
        public string ptollegada { get; set; }
        public string distllegada { get; set; }
        public decimal pdscto { get; set; }
        public decimal dscto { get; set; }
        public string tipodoc { get; set; }
        public string flagCobertura { get; set; }
        public Nullable<System.DateTime> Fecha_web { get; set; }
        public Nullable<bool> statusWeb { get; set; }
        public Nullable<bool> Aprobado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETPEDIDO> DETPEDIDO { get; set; }
        public virtual FORMAPAGO FORMAPAGO1 { get; set; }
        public virtual PERSONAL PERSONAL1 { get; set; }
    }
}
