//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Reporte
    {
        public int PKID { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public int IDVistaReporte { get; set; }
        public bool Activo { get; set; }
        public int IDUsuarioConfiguracion { get; set; }
        public int Tipo { get; set; }
        public System.Guid Registro { get; set; }

        public virtual TipoReporte TipoReporte { get; set; }
        public virtual VistaReporte VistaReporte { get; set; }
    }
}
