//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaAdministrativa
    {
        public int PKID { get; set; }
        public string Vista { get; set; }
        public int IDModulo { get; set; }
        public System.Guid Registro { get; set; }
    
        public virtual Modulo Modulo { get; set; }
    }
}
