//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vva_Producto
    {
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Unidad { get; set; }
        public decimal Fisico { get; set; }
        public Nullable<decimal> Disponible { get; set; }
        public string IDProv { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string IDMarca { get; set; }
        public string IDLinea { get; set; }
        public string IDGrupo { get; set; }
        public string IDCategoria { get; set; }
        public string IDClase { get; set; }
        public Nullable<decimal> C_MENOR { get; set; }
        public Nullable<decimal> C_MAYOR { get; set; }
        public Nullable<decimal> CR_MENOR { get; set; }
        public Nullable<decimal> CR_MAYOR { get; set; }
        public Nullable<decimal> ESPECIAL05 { get; set; }
        public Nullable<decimal> ESPECIAL06 { get; set; }
        public decimal ESPECIAL07 { get; set; }
        public string sku { get; set; }
        public string EAN { get; set; }
        public Nullable<int> factor { get; set; }
        public Nullable<int> FP { get; set; }
        public bool Web { get; set; }
        public bool Dms { get; set; }
        public bool Activo { get; set; }
        public bool Afecto { get; set; }
        public int Unidades { get; set; }
        public bool ArticuloVenta { get; set; }
        public bool ArticuloCompra { get; set; }
        public bool ArticuloCombo { get; set; }
        public bool percepcion { get; set; }
        public bool detraccion { get; set; }
        public string RowNber { get; set; }
        public Nullable<int> IDUnidad { get; set; }
    }
}
