//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vva_ItemPedido
    {
        public string NrPedido { get; set; }
        public string IDProveedor { get; set; }
        public decimal Precio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string IDProducto { get; set; }
        public decimal TranGratuita { get; set; }
        public Nullable<int> IDBonif { get; set; }
        public Nullable<decimal> PrecioNeto { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Recargo { get; set; }
        public Nullable<decimal> Afecto { get; set; }
    }
}
