//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vva_ItemCp
    {
        public string NrDoc { get; set; }
        public string TpDoc { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string IDProveedor { get; set; }
        public string IDProducto { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string TpPrecio { get; set; }
        public Nullable<decimal> igv { get; set; }
        public int Anulado { get; set; }
        public Nullable<decimal> pdscto { get; set; }
        public Nullable<decimal> totdscto { get; set; }
        public decimal percepcion { get; set; }
        public decimal detraccion { get; set; }
        public int Signo { get; set; }
        public Nullable<int> IDBonificacion { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> PrecioNeto { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Recargo { get; set; }
        public Nullable<bool> Afecto { get; set; }
        public Nullable<bool> Bonif { get; set; }
    }
}
