//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Vva_Cliente
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Zona { get; set; }
        public string Tipo { get; set; }
        public string Documento { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechIng { get; set; }
        public Nullable<int> TopeCredito { get; set; }
        public string Telefono { get; set; }
        public decimal Saldo { get; set; }
        public bool Credito { get; set; }
        public string IDDistrito { get; set; }
        public string IDNegocio { get; set; }
        public Nullable<byte> Clase { get; set; }
    }
}
