//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Vva_Vendedor
    {
        public string Codigo_vendedor { get; set; }
        public string Nombre_Vendedor { get; set; }
        public string TipoPersona { get; set; }
        public string Doc_Identidad { get; set; }
        public bool Activo { get; set; }
        public int TpLista { get; set; }
        public string IDGrupo { get; set; }
        public string IDFzaVentas { get; set; }
    }
}
