//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Vva_ListadoPorRuta
    {
        public string Proveedor { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Vendedor { get; set; }
        public string Orden { get; set; }
        public string Zona { get; set; }
        public string Ruta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Gestion { get; set; }
    }
}
