//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xtraForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vva_Pedido
    {
        public string NrPedido { get; set; }
        public string IDVend { get; set; }
        public string IDClient { get; set; }
        public string TpPago { get; set; }
        public int Credito { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public string TpPersona { get; set; }
        public bool Procesado { get; set; }
        public string TpDoc { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public Nullable<bool> Bajado { get; set; }
        public string Gestion { get; set; }
        public bool Aprobado { get; set; }
    }
}
